// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RiversAPI.Models;

namespace RiversAPI.Migrations
{
    [DbContext(typeof(RiversAPIContext))]
    [Migration("20191028174046_seeding")]
    partial class seeding
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("RiversAPI.Models.River", b =>
                {
                    b.Property<int>("RiverId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Flow");

                    b.Property<string>("Length");

                    b.Property<string>("Mouth");

                    b.Property<string>("Name");

                    b.Property<string>("Source");

                    b.Property<string>("States");

                    b.Property<string>("Tributaries");

                    b.HasKey("RiverId");

                    b.ToTable("Rivers");

                    b.HasData(
                        new
                        {
                            RiverId = 1,
                            Flow = "265,000 cu ft/s ",
                            Length = "1,243 miles",
                            Mouth = "Pacific Ocean",
                            Name = "Columbia River",
                            Source = "Columbia Lake",
                            States = "Washington, Oregon, British Columbia",
                            Tributaries = "Spillimacheen River, Beaver River, Illecillewaet River, Incomappleux River, Kootenay River, Pend Oreille River, Spokane River, Crab Creek, Snake River, John Day River, Deschutes River, Willamette River, Kicking Horse River, Blaeberry River, Canoe River, Kettle River, Sanpoil River, Okanogan River, Entiat River, Wenatchee River, Yakima River, Lewis River, Cowlitz River"
                        },
                        new
                        {
                            RiverId = 2,
                            Flow = "33,010 cu ft/s",
                            Length = "187 miles",
                            Mouth = "Columbia River",
                            Name = "Willamette River",
                            Source = "Coast Fork Willamette River and Middle Fork Willamette River",
                            States = "Oregon",
                            Tributaries = "Coast Fork Willamette River, Long Tom River, Marys River, Luckiamute River, Yamhill River, Tualatin River, Middle Fork Willamette River, McKenzie River, Calapooia River, Santiam River, Molalla River, Clackamas River"
                        },
                        new
                        {
                            RiverId = 3,
                            Flow = "5,824 cu ft/s",
                            Length = "252 miles",
                            Mouth = "Columbia River",
                            Name = "Deschutes River",
                            Source = "Little Lava Lake",
                            States = "Oregon",
                            Tributaries = "Cultus River, Fall River, Little Deschutes River, Spring River, Metolius River, Crooked River, Warm Springs River, White River"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
