// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RiversAPI.Models;

namespace RiversAPI.Migrations
{
    [DbContext(typeof(RiversAPIContext))]
    [Migration("20191028164218_corrected")]
    partial class corrected
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("RiversAPI.Models.River", b =>
                {
                    b.Property<int>("RiverId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Flow");

                    b.Property<string>("Length");

                    b.Property<string>("Mouth");

                    b.Property<string>("Name");

                    b.Property<string>("Source");

                    b.Property<string>("States");

                    b.Property<string>("Tributaries");

                    b.HasKey("RiverId");

                    b.ToTable("Rivers");
                });
#pragma warning restore 612, 618
        }
    }
}
